# version format
version: 0.0.{build}-{branch}
skip_tags: true
clone_folder: c:\gopath\src\github.com\dgodd\pulsego
environment:
  GOPATH: c:\gopath
  GOROOT: c:\go
install:
  - go get -v github.com/onsi/ginkgo/ginkgo
  - go get -v github.com/onsi/gomega
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin
test_script:
  - ginkgo -r --randomizeAllSpecs --randomizeSuites --failOnPending --cover --trace --race --compilers=2
notifications:
    # Webhook
    # http://requestb.in/umqk7hum?inspect
    - provider: Webhook
      url: http://requestb.in/umqk7hum
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: true
# notifications:
#     # Webhook
#     - provider: Webhook
#       url: http://www.myhook2.com
#       headers:
#         User-Agent: myapp 1.0
#         Authorization:
#           secure: GhD+5xhLz/tkYY6AO3fcfQ==
#       on_build_success: true
#       on_build_failure: true
#       on_build_status_changed: true
